In [1]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [3]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [10]:
int_to_char = dict(enumerate(alphabets))

In [12]:
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [13]:
char_to_int = dict((v,i) for i, v in enumerate(alphabets))

In [14]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

##### Data Preparation

In [74]:
seq_length = 1
x = []
y = []
for i in range(len(alphabets)-seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1]
    x += [[char_to_int[seq_in[0]]]]
    y += [char_to_int[seq_out]]
    print(seq_in,'->',seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


In [75]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [76]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

##### Prepare the output variable

In [77]:
from keras.utils import to_categorical

In [78]:
y_new = to_categorical(y)

In [79]:
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

##### Prepare input variables

In [80]:
import numpy as np

In [81]:
x = np.reshape(x, (25,1,1))

In [82]:
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [83]:
x.shape

(25, 1, 1)

In [84]:
x_new = x / 25

In [85]:
x_new

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [86]:
x_new.shape

(25, 1, 1)

In [87]:
y_new.shape

(25, 26)

##### Create the model

In [88]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, SimpleRNN

In [89]:
model = Sequential()

model.add(Dense(25, input_shape=(1,1), activation='relu'))
model.add(SimpleRNN(32))
model.add(Dense(26, activation = 'softmax'))

##### Compile the model

In [90]:
model.compile(loss='categorical_crossentropy', optimizer='adam',
             metrics=['accuracy'])

##### Train the model

In [91]:
model.fit(x_new, y_new, epochs=500, batch_size=1)

Epoch 1/500
25/25 [==============================] - 1s 1ms/step - loss: 3.2860 - accuracy: 0.0000e+00
Epoch 2/500
25/25 [==============================] - 0s 1ms/step - loss: 3.2563 - accuracy: 0.0000e+00
Epoch 3/500
25/25 [==============================] - 0s 1ms/step - loss: 3.2436 - accuracy: 0.0000e+00
Epoch 4/500
25/25 [==============================] - 0s 4ms/step - loss: 3.2301 - accuracy: 0.0400
Epoch 5/500
25/25 [==============================] - 0s 980us/step - loss: 3.2212 - accuracy: 0.0000e+00
Epoch 6/500
25/25 [==============================] - 0s 875us/step - loss: 3.2088 - accuracy: 0.0000e+00
Epoch 7/500
25/25 [==============================] - 0s 2ms/step - loss: 3.1972 - accuracy: 0.0400
Epoch 8/500
25/25 [==============================] - 0s 2ms/step - loss: 3.1838 - accuracy: 0.0400
Epoch 9/500
25/25 [==============================] - 0s 2ms/step - loss: 3.1713 - accuracy: 0.0000e+00
Epoch 10/500
25/25 [==============================] - 0s 2ms/step - loss: 3.1592 

In [92]:
model.evaluate(x_new, y_new, batch_size=1)

25/25 [==============================] - 0s 1ms/step - loss: 1.0380 - accuracy: 0.9600


[1.0379749536514282, 0.9599999785423279]

##### Predict the character in sequence

In [98]:
new = 'E'
new = char_to_int[new]
new = np.reshape(new,(1,1,1))
new = new / 25
pred = model.predict(new)
pred = np.argmax(pred)
int_to_char[pred]

1/1 [==============================] - 0s 13ms/step


'F'

In [57]:
seq_length = 3
x = []
y = []
for i in range(len(alphabets) - seq_length):
  seq_in = alphabets[i:i + seq_length]
  seq_out = alphabets[i + seq_length]
  x.append([char_to_int[char] for char in seq_in])
  y.append(char_to_int[seq_out])
  print(seq_in,'->',seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [58]:
x = np.reshape(x, (len(x), seq_length, 1))

In [60]:
x.shape

(23, 3, 1)

In [61]:
x = x / 25

In [62]:
model = Sequential()

model.add(Dense(25, input_shape=(3,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation = 'softmax'))

In [64]:
y_new = to_categorical(y)
y_new.shape

(23, 26)

In [65]:
# Compile the model
model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

In [68]:
# Train the model
model.fit(x, y_new, epochs=500, batch_size=1)

Epoch 1/500
23/23 [==============================] - 0s 7ms/step - loss: 2.8464 - accuracy: 0.2174
Epoch 2/500
23/23 [==============================] - 0s 6ms/step - loss: 2.4347 - accuracy: 0.1739
Epoch 3/500
23/23 [==============================] - 0s 7ms/step - loss: 2.3513 - accuracy: 0.3478
Epoch 4/500
23/23 [==============================] - 0s 5ms/step - loss: 1.2945 - accuracy: 0.4348
Epoch 5/500
23/23 [==============================] - 0s 7ms/step - loss: 0.9207 - accuracy: 0.6087
Epoch 6/500
23/23 [==============================] - 0s 5ms/step - loss: 0.5762 - accuracy: 0.8261
Epoch 7/500
23/23 [==============================] - 0s 6ms/step - loss: 0.4065 - accuracy: 0.8696
Epoch 8/500
23/23 [==============================] - 0s 6ms/step - loss: 0.3077 - accuracy: 0.9565
Epoch 9/500
23/23 [==============================] - 0s 6ms/step - loss: 0.2576 - accuracy: 1.0000
Epoch 10/500
23/23 [==============================] - 0s 6ms/step - loss: 0.2406 - accuracy: 0.9565
Epoch 11/

In [69]:
model.evaluate(x, y_new, batch_size=1)

23/23 [==============================] - 0s 2ms/step - loss: 0.0588 - accuracy: 1.0000


[0.05875599756836891, 1.0]

##### Predict on a new sequence

In [73]:
new = 'MNO'
val = np.array([[char_to_int[x]] for x in new])
val = val.reshape(1,3,1)
val = val / 25
result = model.predict(val)
result = np.argmax(result)
print(int_to_char[result])

1/1 [==============================] - 0s 18ms/step
P
